language: go

go:
  - 1.11

sudo: required
dist: trusty

env:
  - GO111MODULE=on

before_install:
  - sudo apt-get update
  - sudo apt-get install -y gtk+3.0 libgtk-3-dev libcairo2-dev libglib2.0-dev
  - sudo apt-get install -y xvfb
  - "export DISPLAY=:99.0"
  - sudo /usr/bin/Xvfb $DISPLAY 2>1 > /dev/null &
  - "export GTK_VERSION=$(pkg-config --modversion gtk+-3.0 | tr . _| cut -d '_' -f 1-2)"
  - "export Glib_VERSION=$(pkg-config --modversion glib-2.0)"
  - "export Cairo_VERSION=$(pkg-config --modversion cairo)"
  - "export Pango_VERSION=$(pkg-config --modversion pango)"
  - echo "GTK version ${GTK_VERSION} (Glib ${Glib_VERSION}, Cairo ${Cairo_VERSION}, Pango ${Pango_VERSION})"
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.12.3

install: true

script:
  - go build ./...
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
  - golangci-lint run

after_success:
  - bash <(curl -s https://codecov.io/bash)