language: go

go:
  - 1.11

services:
  - docker

env:
  - GO111MODULE=on

sudo: required

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.9.1
  - go mod vendor
  - docker pull golang:1.11
  - echo '#!/bin/sh -e' > build.sh
  - echo 'apt-get update' >> build.sh
  - echo 'apt-get install -y build-essential libgtk-3-dev libcairo2-dev libglib2.0-dev' >> build.sh
  - echo 'go test -v -race -coverprofile=coverage.txt -covermode=atomic $(go list ./... | grep -v "/vendor/")' >> build.sh
  - echo 'golangci-lint run --deadline 10m' >> build.sh
  - chmod +x build.sh

script:
  - docker run --rm -v "$GOPATH":/go -w /go/src/github.com/rvflash/safe golang:1.11 ./build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)